name: Build and Publish image to Docker Hub

on: 
  push:
    branches:
      - main
    paths:
      - 'api/dockerfile'
      - 'front-end-nextjs/dockerfile'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u phuttipong1 --password-stdin

      - name: Build Docker images
        run: |
          docker build -f ./api/dockerfile ./api/ -t phuttipong1/project-api:latest
          docker build -f ./front-end-nextjs/dockerfile ./front-end-nextjs/ -t phuttipong1/project-frontend:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push phuttipong1/project-api:latest
          docker push phuttipong1/project-frontend:latest
