name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest  # ✅ ต้องใช้ขีดกลาง ไม่ใช่ ubuntu_latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u phuttipong1 --password-stdin

      - name: Build Docker images
        run: |
          docker build ./api/ -t phuttipong1/project-api:latest
          docker build ./front-end-nextjs/ -t phuttipong1/project-frontend:latest

      - name: Push Docker images
        run: |
          docker push phuttipong1/project-api:latest
          docker push phuttipong1/project-frontend:latest
