name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'api/dockerfile'
      - 'front-end-nextjs/dockerfile'

jobs:
  Publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build images
        run: |
          docker build ./api/ -t phuttipong1/project-api:latest
          docker build ./front-end-nextjs/ -t phuttipong1/project-frontend:latest

      - name: push images to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u phuttipong1 --password-stdin
          docker push phuttipong1/project-api:latest
          docker push phuttipong1/project-frontend:latest
