name: Build and Publish image to Docker Hub

on: 
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  Publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u phuttipong1 --password-stdin

      - name: Build Docker images
        run: |
          docker build ./api/ -t phuttipong1/project-api:latest
          docker build ./front-end-nextjs/ -t phuttipong1/project-frontend:latest

      - name: Push Docker images
        run: |
          docker push phuttipong1/project-api:latest
          docker push phuttipong1/project-frontend:latest
