name : Build and Publish image to docker Hub
on: 
  push:
    branches:
      - main
    paths:
      - 'api/dockerfile'
      - 'front-end-next/dockerfile'


jobs:
  Publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t phuttipong1/project-web:latest
          docker build ./front-end-nextjs/ -t phuttipong1/project-web:latest
      - name: push image to docker hub
        run: |
          docker login -u phuttipong1 -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push phuttipong1/project-web:latest
      - name: logout from docker hub
        run: |
          docker logout       
      - name: cleanup 
        run: |
          docker rmi phuttipong1/project-web:latest
          docker system prune -f
          docker volume prune -f
          docker network prune -f
          docker image prune -f
          docker container prune -f   


